import { chromium } from 'playwright';
const OUT = process.env.OUT;
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1600, height: 900 } });
page.on('pageerror', (e) => console.log('pageerror:', e.message));
await page.addInitScript(() => { window.__TICKET_TEST__ = true; try { localStorage.clear(); } catch {} });
await page.goto('http://localhost:4317/?source=mock&freeze=1');
await page.waitForFunction(() => window.__ticket && window.__chart);
await page.click('.mode-seg >> text=Easy');
await page.waitForTimeout(500);
await page.screenshot({ path: `${OUT}/e1-cone.png` });
const G = await page.evaluate(() => ({ nowX: window.__chart.geom.nowX, plotR: window.__chart.geom.plotR, spot: window.__chart.spot, pToY: null }));
const box = await page.locator('canvas').first().boundingBox();
const at = async (fx, mult) => page.evaluate(({ fx, mult, G }) => [G.nowX + fx * (G.plotR - G.nowX), window.__chart.pToY(G.spot * mult)], { fx, mult, G });
let [x, y] = await at(0.55, 1.08);
await page.mouse.move(box.x + x, box.y + y); await page.waitForTimeout(300);
console.log('hover quote:', JSON.stringify(await page.evaluate(() => window.__chart.easyHover)));
await page.screenshot({ path: `${OUT}/e2-hover.png` });
await page.mouse.down(); await page.mouse.up(); await page.waitForTimeout(400);
await page.mouse.move(1590, 895);
await page.screenshot({ path: `${OUT}/e3-card.png` });
console.log('card:', (await page.textContent('.bet-card')).slice(0, 200));
await page.click('.stake-quick >> text=$50');
await page.click('.bet-card .primary');
await page.waitForTimeout(400);
[x, y] = await at(0.3, 0.94);
await page.mouse.click(box.x + x, box.y + y); await page.waitForTimeout(300);
await page.click('.bet-card .primary'); await page.waitForTimeout(400);
await page.mouse.move(1590, 895);
await page.screenshot({ path: `${OUT}/e4-bets.png` });
console.log('bets:', await page.$$eval('.bet-list li', (ls) => ls.map((l) => l.innerText.replace(/\n/g, ' | '))));
await browser.close();
